name: Pull Code from Another Repository

on:
  push:
    branches:
      - main
env:
  SOURCE_REPO_OWNER: anniimol
  SOURCE_REPO_NAME: static-testing-demo-iboss
  SOURCE_BRANCH: main

jobs:
  pull-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Pull code from another repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.SOURCE_REPO_OWNER }}/${{ env.SOURCE_REPO_NAME }}
          ref: ${{ env.SOURCE_BRANCH }}
      - name: check
        run: ls



# name: Push-to-EC2

# # Trigger deployment only on push to main branch
# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: Deploy to EC2 on main branch push
#     runs-on: ubuntu-latest
#     steps:
#     #checkout the code from github
#       - name: Checkout the files
#         uses: actions/checkout@v2
        
#     #Deploty the code to target server
#       - name: Deploy to Server 1
#         uses: easingthemes/ssh-deploy@main
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
#           REMOTE_HOST: ${{ secrets.HOST_DNS }}
#           REMOTE_USER: ${{ secrets.USERNAME }}
#           TARGET: /var/www/html
          
# #     #push the code to amazon s3 bucket
# #       - uses: jakejarvis/s3-sync-action@master
# #         with:
# #           args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
# #         env:
# #           AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
# #           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
# #           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
